version: 2.1

references:
  # cache configs
  restore_repo: &restore_repo
    restore_cache:
      name: Restore Repo Cache
      keys:
        - v1-repo-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ .Revision }}

  default_container_config: &default_container_config
    docker:
      - image: circleci/node:latest
  # configuration for golang
  go_container_config: &go_container_config
    docker:
      - image: circleci/golang:1.12

jobs:
  checkout_code:
    <<: *default_container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ .Revision }}
          paths:
            - .

  server_tests:
    # references golang container configration
    <<: *go_container_config
    steps:
      - *restore_repo
      - run:
          name: "Unit Tests"
          command: go test -v ./...

workflows:
  version: 2
  ci: 
    jobs:
      - checkout_code
      - server_tests:
          requires:
            - checkout_code